### ISSUE TITLE
hi Author

### ISSUE THREAD

**Issue by DuongVu29** [qjon/angular2-tree#14]
hi author, I love the display of the second tree in your demo, I am trying to use it for my demo project, but unfortunately, I can not make it run following you instruction. could you please help to give more details on how to use it. I get this error while trying to build the demo 
Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (D:\angular2-tree-master\node_modules\angular-cli\tasks\serve.js:22:61)
    at D:\angular2-tree-master\node_modules\angular-cli\commands\serve.run.js:22:22
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Regards,

**Comment by qjon** [comment]
HI,

Do you try to run my demo? If yes you have only clone my git repository install all dependencies with _npm_ and strat app. But if you try to use the second try layout by injecting this module to your project - it is impossible, because this layout is only in demo, not in module.

If you have still problem, please give me more information, because this above error does not tell me anything.
